apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - observability-project.yaml
  - observability-namespace.yaml
  - observability-metrics-server.yaml
  - observability-kube-prometheus-stack.yaml
