apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: observability
  source:
    repoURL: https://github.com/REPLACE_ME/homelab-config.git
    targetRevision: main
    path: apps/observability/metrics-server
    helm:
      releaseName: metrics-server
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
